from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from conf import *


def dump_entry(f, entry, prefix="CONFIG_"):
    match entry.type:
        case ConfigType.BOOL:
            f.write(f"#define {prefix}{entry.name} {1 if entry.value else 0}\n")
        case ConfigType.INT:
            f.write(f"#define {prefix}{entry.name} {entry.value}\n")
        case ConfigType.STRING:
            f.write(f'#define {prefix}{entry.name} "{entry.value}"\n')
        case ConfigType.CHOICE:
            opt = ""
            for choice,i in zip(entry.choices, range(len(entry.choices))): 
                f.write(f"#define {prefix}{entry.name}_{choice["name"].upper()} {i}\n")
                if entry.value == choice["name"]:
                    opt = f"{prefix}{entry.name}_{choice['name'].upper()}"
            f.write(f"#define {prefix}{entry.name} {opt}\n")
        case ConfigType.MENU | ConfigType.DYNAMICMENU:
            for e in entry.children:
                dump_entry(f, e, prefix=prefix + entry.name + "_")
        case ConfigType.TRISTATE:
            f.write(
                f"#define {prefix}{entry.name} {2 if entry.value == 'm' else 1 if entry.value == 'y' else 0}\n"
            )
        case _:
            raise ValueError(f"Unknown type: {entry.type}")


def generate_func_main(opt: list[ConfigOption]) -> list[str]:
    with open(args.header, "w") as f:
        f.write("// This file is generated\n")
        f.write("// Do not edit this file directly\n")
        f.write("#pragma once\n")

        for entry in opt:
            if entry.name == "MODULES" or entry.name == "TOOLS":
                continue
            dump_entry(f, entry)
    return [args.header]


@register_generator
def gen():
    return Generator(
        name="Main config header generator",
        description="Generate a header file for main config",
        gen=generate_func_main,
    )


# Vim: set expandtab tabstop=4 shiftwidth=4:
