from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from conf import *


def dump_entry(f, entry, prefix="CONFIG_"):
    match entry.type:
        case ConfigType.BOOL:
            f.write(f"#define {prefix}{entry.name} {1 if entry.value else 0}\n")
        case ConfigType.INT:
            f.write(f"#define {prefix}{entry.name} {entry.value}\n")
        case ConfigType.STRING:
            f.write(f'#define {prefix}{entry.name} "{entry.value}"\n')
        case ConfigType.CHOICE:
            f.write(f"#define {prefix}{entry.name} {entry.value}\n")
        case ConfigType.MENU | ConfigType.DYNAMICMENU:
            for e in entry.children:
                dump_entry(f, e, prefix=prefix+entry.name+"_")
        case ConfigType.TRISTATE:
            f.write(
                f"#define {prefix}{entry.name} {2 if entry.value == 'm' else 1 if entry.value == 'y' else 0}\n"
            )
        case _:
            raise ValueError(f"Unknown type: {entry.type}")


def generate_func(opt: list[ConfigOption]) -> list[str]:
    gen_files = []
    plugins_opt = next((o for o in opt if o.name == "MODULES"), None)
    if not plugins_opt:
        return []
    for plugin in plugins_opt.children:
        plugin_name = os.path.dirname(plugin.source_file).split("/")[-1].upper()
        file_name = os.path.dirname(plugin.source_file) + f"/include/{plugin_name.lower()}_config.hpp"
        with open(file_name, "w") as f:
            f.write("// This file is generated\n")
            f.write("// Do not edit this file directly\n")
            f.write("#pragma once\n")

            for entry in plugin.children:
                dump_entry(f, entry, prefix=f"CONFIG_{plugin_name}_")
        gen_files.append(file_name)
    return gen_files


@register_generator
def gen():
    return Generator(
        name="test2",
        description="A test2 generator",
        gen=generate_func,
    )


# Vim: set expandtab tabstop=4 shiftwidth=4:
