from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from conf import *


def dump_entry(f, entry: ConfigOption, xmacros, prefix="CONFIG_"):
    match entry.type:
        case ConfigType.BOOL:
            f.write(f"#define {prefix}{entry.name} {1 if entry.value else 0}\n")
            if entry.runtime_export:
                xmacros.append(f'X("{entry.name.lower()}", {1 if entry.value else 0})')
        case ConfigType.INT:
            f.write(f"#define {prefix}{entry.name} {entry.value}\n")
            if entry.runtime_export:
                xmacros.append(f'X("{entry.name.lower()}", {entry.value})')
        case ConfigType.STRING:
            f.write(f'#define {prefix}{entry.name} "{entry.value}"\n')
            if entry.runtime_export:
                xmacros.append(f'X("{entry.name.lower()}", "{entry.value}")')
        case ConfigType.CHOICE:
            opt = ""
            for choice, i in zip(entry.choices, range(len(entry.choices))):
                f.write(f"#define {prefix}{entry.name}_{choice["name"].upper()} {i}\n")
                if entry.value == choice["name"]:
                    opt = f"{prefix}{entry.name}_{choice['name'].upper()}"
            f.write(f"#define {prefix}{entry.name} {opt}\n")
            if entry.runtime_export:
                xmacros.append(f'X("{entry.name.lower()}", {opt})')
        case ConfigType.MENU | ConfigType.DYNAMICMENU:
            for e in entry.children:
                dump_entry(f, e, xmacros, prefix=(prefix + entry.name + "_"))
        case ConfigType.TRISTATE:
            f.write(
                f"#define {prefix}{entry.name} {2 if entry.value == 'm' else 1 if entry.value == 'y' else 0}\n"
            )
            if entry.runtime_export:
                xmacros.append(
                    f"X(\"{entry.name.lower()}\", {2 if entry.value == 'm' else 1 if entry.value == 'y' else 0})"
                )
        case _:
            raise ValueError(f"Unknown type: {entry.type}")



def pl_generate_func(opt: list[ConfigOption]) -> list[str]:
    gen_files = []
    plugins_opt = next((o for o in opt if o.name == "MODULES"), None)
    if not plugins_opt:
        return []
    for plugin in plugins_opt.children:
        plugin_name = os.path.dirname(plugin.source_file).split("/")[-1].upper()
        file_name = (
            os.path.dirname(plugin.source_file)
            + f"/include/{plugin_name.lower()}_config.hpp"
        )
        with open(file_name, "w") as f:
            xmacros = []
            f.write("// This file is generated\n")
            f.write("// Do not edit this file directly\n")
            f.write("#pragma once\n")

            for entry in plugin.children:
                dump_entry(f, entry, xmacros, prefix=f"CONFIG_{plugin_name}_")

            if xmacros:
                f.write("\n// X-Macros\n")
                f.write("#define CONFIG_OPTS \\\n")
                for xm in xmacros:
                    if xm == xmacros[-1]:
                        f.write(f"  {xm}\n")
                    else:
                        f.write(f"  {xm} \\\n")
        gen_files.append(file_name)
    return gen_files


def tl_generate_func(opt: list[ConfigOption]) -> list[str]:
    gen_files = []
    tools_opt = next((o for o in opt if o.name == "TOOLS"), None)
    if not tools_opt:
        return []
    for tool in tools_opt.children:
        tool_name = os.path.dirname(tool.source_file).split("/")[-1].upper()
        file_name = (
            os.path.dirname(tool.source_file)
            + f"/include/{tool_name.lower()}_config.hpp"
        )
        with open(file_name, "w") as f:
            xmacros = []
            f.write("// This file is generated\n")
            f.write("// Do not edit this file directly\n")
            f.write("#pragma once\n")

            for entry in tool.children:
                dump_entry(f, entry, xmacros, prefix=f"CONFIG_{tool_name}_")

            if xmacros:
                f.write("\n// X-Macros\n")
                f.write("#define CONFIG_OPTS \\\n")
                for xm in xmacros:
                    if xm == xmacros[-1]:
                        f.write(f"  {xm}\n")
                    else:
                        f.write(f"  {xm} \\\n")
        gen_files.append(file_name)
    return gen_files


def generate_func_pl(opt: list[ConfigOption]) -> list[str]:
    return pl_generate_func(opt) + tl_generate_func(opt)


@register_generator
def gen():
    return Generator(
        name="Plugin config header generator",
        description="Generate a header file for plugin config",
        gen=generate_func_pl,
    )


# Vim: set expandtab tabstop=4 shiftwidth=4:
