from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from conf import *


def generate_func_tls(opts: list[ConfigOption]) -> list[str]:
    target = os.path.join(os.path.realpath(os.path.dirname(args.header)), "tls_includer.hpp")
    bo_opts = ConfigOption
    for opt in opts:
        if opt.name == "BO":
            bo_opts = opt

    tls_opt = ConfigOption
    for opt in bo_opts.children:
        if opt.name == "TLS_BACKEND":
            tls_opt = opt

    with open(target, "w") as f:
        f.write("// This file is generated\n")
        f.write("// Do not edit this file directly\n")
        f.write("#pragma once\n")

        for choice in tls_opt.choices:
            f.write(f"#if CONFIG_BO_TLS_BACKEND == CONFIG_BO_TLS_BACKEND_{choice["name"].upper()}\n")
            f.write(f"#include \"lib/tls/{choice["name"].lower()}.hpp\"\n")
            f.write("#endif\n")

    return [target]

@register_generator
def gen():
    return Generator(
        name="Plugin config header generator",
        description="Generate a header file for plugin config",
        gen=generate_func_tls,
    )
