- name: MAKE_EXECUTABLE
  prompt: Make executable
  type: bool
  help_text: Make executable for the tool.
  cmake_export: true
  default: true
  runtime_export: false

- name: LINK_STATIC
  prompt: Link static
  type: bool
  help_text: Link static for the tool.
  cmake_export: true
  default: false
  runtime_export: false

- name: ENABLE_LOGGING
  prompt: Enable logging
  type: bool
  help_text: Enable logging for the tool.
  cmake_export: true
  default: true

- name: FUSE
  prompt: FUSE options
  type: menu
  source: fuse.yaml
