- name: ENABLE_TESTS
  prompt: Enable Tests
  type: bool
  default: true
  help_text: Enable or disable building tests.
  cmake_export: true
  cmake_help: $help_text$

- name: ENABLE_SANITIZERS
  prompt: Enable Sanitizers
  type: bool
  default: false
  help_text: Enable or disable building with sanitizers (e.g., AddressSanitizer, UndefinedBehaviorSanitizer).
  cmake_export: true
  cmake_help: $help_text$ 

- name: ENABLE_PCH
  prompt: Enable Precompiled Headers
  type: bool
  default: true
  help_text: Enable or disable the use of precompiled headers to speed up compilation.
  cmake_export: true
  cmake_help: $help_text$
