- name: CONFIG_PROJECT_NAME
  prompt: Project Name
  type: string
  default: explo
  help_text: Help Text

- name: CONFIG_MODULES
  prompt: Module options
  type: dynamicmenu
  source: modules/*/config.yaml
  help_text: Select module options.
