- name: PLUGIN_INSTALL_DIR
  prompt: Plugin install directory
  type: string
  default: plugins
  help_text: Directory where plugins will be loaded from.

- name: LOG_FILE
  prompt: Log file
  type: string
  default: explo.log
  help_text: Log file name.

- name: LOG_DIR
  prompt: Log directory
  type: string
  default: logs
  help_text: Directory where logs will be placed.

- name: CONFIG_FILE
  prompt: Default config file
  type: string
  default: config
  help_text: Default configuration file to use if no other is specified.

- name: SESSION_STORE
  prompt: Default session store
  type: string
  default: sessions.yaml
  help_text: Default session store file to use if no other is specified.

- name: SESSION_SOCKET
  prompt: Default session socket
  type: string
  default: /tmp/explo/session.sock
  help_text: Default session socket to use if no other is specified.

- name: SESSION_HEARTBEAT
  prompt: Session heartbeat interval
  type: int
  default: 5
  help_text: Interval in seconds for session heartbeat checks.

- name: CONFIG_DIR
  prompt: Config directory
  type: string
  default: configs
  help_text: Directory where plugin configuration files will be loaded from.

- name: PREFERRED_UI
  prompt: Default UI type
  type: string
  default: simple_ui
  help_text: Default UI type to use if no other is specified.

- name: BO
  prompt: Build options
  type: menu
  source: build_options.yaml

- name: MODULES
  prompt: Module options
  type: dynamicmenu
  source: plugins/*/config.yaml
  help_text: Select module options.
  help_text_fmt: Options for {filename} plugin.

- name: TOOLS
  prompt: Tool options
  type: dynamicmenu
  source: tools/*/config.yaml
  help_text: Select tool options.
  help_text_fmt: Options for {filename} tool.

- name: LIB
  prompt: Library options
  type: menu
  source: lib.yaml
  help_text: Select library options.
